# Generated by Django 4.1 on 2022-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('class_name', models.IntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.IntegerField(blank=True, editable=False)),
            ],
        ),
    ]
